name: Dev CI/CD Pipeline

on:
  push:
    branches:
      - feature/**
      - main
    paths:
      - vote/**
      - worker/**
      - result/**
  pull_request:
    branches:
      - feature/**
    paths:
      - vote/**
      - worker/**
      - result/**
      - .github/workflows/dev.yml

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push vote image
        run: |
          docker build -t ghcr.io/jruiz1601/vote:${{ github.sha }} ./vote
          docker push ghcr.io/jruiz1601/vote:${{ github.sha }}

      - name: Build and push worker image
        run: |
          docker build -t ghcr.io/jruiz1601/worker:${{ github.sha }} ./worker
          docker push ghcr.io/jruiz1601/worker:${{ github.sha }}

      - name: Build and push result image
        run: |
          docker build -t ghcr.io/jruiz1601/result:${{ github.sha }} ./result
          docker push ghcr.io/jruiz1601/result:${{ github.sha }}

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: >-
            {"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group microservices-demo-rg --name microservices-demo-aks --overwrite-existing

      - name: Deploy vote
        run: |
          helm upgrade --install vote ./vote/chart \
            --set image=ghcr.io/jruiz1601/vote:${{ github.sha }}

      - name: Deploy worker
        run: |
          helm upgrade --install worker ./worker/chart \
            --set image=ghcr.io/jruiz1601/worker:${{ github.sha }}

      - name: Deploy result
        run: |
          helm upgrade --install result ./result/chart \
            --set image=ghcr.io/jruiz1601/result:${{ github.sha }}